# MD5: 72d48ea565b8a466587e07434e847d4f
set(CFG_BBP_MASTER_NONE 0) 

set(CFG_BBP_MASTER_V8R1 1) 

set(CFG_BBP_MASTER_V7R5 2) 

set(CFG_BBP_MASTER_V8R5 3) 

set(CFG_BBP_MASTER_K3V6 4) 

set(CFG_BBP_MASTER_KIRIN970 5) 

set(CFG_FEATURE_BBP_MASTER_VER (BBP_MASTER_K3V6)) 

set(CFG_FEATURE_BBP_MASTER FEATURE_ON) 

set(CFG_BBP_MASTER_INT_MODE FEATURE_ON) 

set(CFG_FEATURE_BBP_MASTER_CHAN_EXTEND FEATURE_ON) 

set(CFG_FEATURE_BBP_MASTER_CHAN_U2 FEATURE_ON) 

set(CFG_FEATURE_POWER_TIMER FEATURE_ON) 

set(CFG_FEATURE_UE_UICC_MULTI_APP_SUPPORT FEATURE_ON) 

set(CFG_FEATURE_VSIM FEATURE_ON) 

set(CFG_FEATURE_GUC_BBP_TRIG FEATURE_ON) 

set(CFG_FEATURE_GUBBP_HANDSHAKE FEATURE_ON) 

set(CFG_FEATURE_GUDRX_NEWVERSION FEATURE_ON) 

set(CFG_FEATURE_VOS_REDUCE_MEM_CFG FEATURE_OFF) 

set(CFG_FEATURE_OM_BBPLOG FEATURE_OFF) 

set(CFG_FEATURE_RTC_TIMER_DBG FEATURE_ON) 

set(CFG_FEATURE_PHONE_SC FEATURE_ON) 

set(CFG_FEATURE_SC_SEC_UPDATE FEATURE_ON) 

set(CFG_FEATURE_VSIM_ICC_SEC_CHANNEL FEATURE_ON) 

